import React from "react";
import Link from "next/link";
import { MdArrowOutward } from "react-icons/md";
import { caseStudies } from "@/content/work";
import StructuredData from "@/components/shared/StructuredData";
import { pageMetadata } from "@/lib/metadata";
import { workIndexSchema } from "@/lib/schema";

export const metadata = pageMetadata({
  title: "Work",
  path: "/work",
  description:
    "Six systems I've built — recommendation engines, agentic copilots, meeting intelligence, and the platform underneath them — written up with the architecture and the trade-offs.",
  socialTitle: "Work | Harsh Keshari",
  type: "website",
  // Its own card is generated by opengraph-image.tsx in this folder.
  image: false,
});

/**
 * /work used to 404. Two of the six studies — recommender and learning-copilot
 * — were reachable only by clicking a node inside a diagram on a third study,
 * so a visitor could find four of six and a crawler had only the sitemap.
 *
 * Order is the `caseStudies` array order, which already puts the two services
 * ahead of the platform study that contains them.
 */
export default function WorkIndex() {
  return (
    <div className="w-full min-h-[100svh] px-6 md:px-16 pt-10 md:pt-16 pb-28 md:pb-16">
      <StructuredData data={workIndexSchema(caseStudies)} />
      <div className="max-w-4xl">
        <Link
          href="/"
          className="text-xs text-neutral-400 hover:text-amber-400 transition-colors duration-150"
        >
          ← Home
        </Link>

        <header className="mt-5">
          <h1 className="font-Rampart text-5xl md:text-7xl text-white leading-none">
            Work.
          </h1>
          <p className="text-base text-neutral-300 max-w-xl leading-relaxed mt-5">
            Six systems, written up with the architecture and the parts that
            broke. The through-line is the same argument each time: a validation
            layer that can be bypassed by its own failure path is not a
            validation layer.
          </p>
        </header>

        <ul className="mt-12 space-y-4">
          {caseStudies.map((study) => (
            <li key={study.slug}>
              <Link
                href={`/work/${study.slug}`}
                aria-label={`Read the ${study.title} case study`}
                className="group block border border-neutral-800 rounded-2xl p-6 bg-neutral-900/40 hover:border-neutral-700 transition-colors duration-150"
              >
                <div className="flex items-center gap-3 flex-wrap">
                  <h2 className="text-xl font-semibold text-white">
                    {study.title}
                  </h2>
                  {study.org && (
                    <span className="text-[10px] tracking-[0.12em] uppercase px-2.5 py-1 rounded-full border border-neutral-700 text-neutral-300">
                      {study.org}
                    </span>
                  )}
                  <span className="text-xs text-neutral-500">
                    {study.period}
                  </span>
                </div>

                <p className="text-sm text-neutral-400 leading-relaxed max-w-2xl mt-2">
                  {study.summary}
                </p>

                <div className="flex items-center gap-2 flex-wrap mt-4">
                  {study.tags.slice(0, 6).map((t) => (
                    <span
                      key={t}
                      className="text-xs px-2 py-0.5 rounded-full border border-neutral-700 text-neutral-400"
                    >
                      {t}
                    </span>
                  ))}
                </div>

                <span className="inline-flex items-center gap-1.5 text-sm font-medium text-amber-400 mt-4">
                  Read the case study
                  <MdArrowOutward className="w-3.5 h-3.5" aria-hidden="true" />
                </span>
              </Link>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}
